### ISSUE TITLE
[控制台语法错误]您的代码中main.vue和nav.vue中的控制台输出不正确

### ISSUE THREAD

**Issue by 2926295173** [lework/lenav#12]
Vue3.0 console.log()语法报错

只需要改成window.console.log() 即可解决

**Comment by lework** [comment]
能给个截图么？我没看到有错误显示。

**Comment by 2926295173** [comment]
啊这，我已经修改完了?😂

**Comment by 2926295173** [comment]
这是之前我没修复的时候的，给您看下参考![Screenshot_20210419_195154_mark.via.jpg](https://user-images.githubusercontent.com/74408214/115232020-d8167600-a148-11eb-8e11-ef385d8d974a.jpg)

**Comment by lework** [comment]
修正了。

**Comment by 2926295173** [comment]
辛苦了(≧∇≦)/
