### ISSUE TITLE
【功能建议】添加二级菜单

### ISSUE THREAD

**Issue by 2926295173** [lework/lenav#15]
网址导航的网站越来越多，能否添加个二级菜单，将分类再细分一下。

我提供个思路：把原来的导航菜单下加个子菜单【实质就是原来的菜单变成了收藏夹，点击可以展开，但是页面不动】，点击子菜单某个项目时，展示内容上下滑动到相应位置

**Comment by 2926295173** [comment]
![Screenshot_20210425_194257_mark.via.jpg](https://user-images.githubusercontent.com/74408214/115992107-86656400-a5fe-11eb-9a77-b03890003d9c.jpg)
另外，手机的显示有点问题，产生了遮挡，您看是否能更改下优先级

**Comment by lework** [comment]
嗯，功能添加好了，遮挡修复了。

**Comment by beiguancyc** [comment]
> 嗯，功能添加好了，遮挡修复了。

build失败

**Comment by 2926295173** [comment]
> > 嗯，功能添加好了，遮挡修复了。
> 
> build失败

是否有log截图

**Comment by beiguancyc** [comment]
![image](https://user-images.githubusercontent.com/12932389/116634788-9dee7500-a98f-11eb-89b8-d1cd699b3f32.png)
